/*
# Create gifts table for ForYou

## Overview
Stores personalized digital gifts created by users. Each gift has a unique short ID
that is used in the shareable URL (/gift/<id>). Gifts are protected by a password
that the recipient must enter to unlock the reveal animation.

## New Tables
- `gifts`
  - `id` (text, primary key) — short unique alphanumeric code (e.g. "7K92X"), generated by the app
  - `recipient_name` (text, not null) — who the gift is for
  - `message` (text, not null) — the personal message shown after unlock
  - `occasion` (text, not null) — Birthday, Graduation, Congratulations, Thank You, Miss You, Love
  - `experience_type` (text, not null) — envelope, gift, balloon, wish, secret
  - `password_hash` (text, not null) — SHA-256 hash of the creator-set password (hashed server-side via edge function)
  - `password_hint` (text) — optional hint shown to the recipient
  - `creator_name` (text) — optional name of the person creating the gift
  - `created_at` (timestamptz, default now())

## Security
- RLS enabled on `gifts`.
- This is a no-auth public app: anyone can create a gift and anyone with the link + password can open it.
- Policies use `TO anon, authenticated` so the anon-key frontend can read and insert.
- SELECT is intentionally public (gifts are meant to be opened via shared link).
- INSERT is public (anyone can create a gift).
- UPDATE and DELETE are disabled (no policy) — once created, a gift is immutable.

## Important Notes
1. The password is NEVER stored in plaintext. The app hashes the password with SHA-256
   before sending it to the database. The recipient's entered password is also hashed
   client-side and compared client-side for the prototype. For production, password
   verification should happen server-side via an edge function (structured in code to allow this).
2. The gift ID is a short 5-character alphanumeric code generated client-side and checked
   for uniqueness before insert.
3. No user_id / auth is used — this is a single-tenant public app.
*/

CREATE TABLE IF NOT EXISTS gifts (
  id text PRIMARY KEY,
  recipient_name text NOT NULL,
  message text NOT NULL,
  occasion text NOT NULL,
  experience_type text NOT NULL,
  password_hash text NOT NULL,
  password_hint text,
  creator_name text,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE gifts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_gifts" ON gifts;
CREATE POLICY "anon_select_gifts"
ON gifts FOR SELECT
TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_gifts" ON gifts;
CREATE POLICY "anon_insert_gifts"
ON gifts FOR INSERT
TO anon, authenticated WITH CHECK (true);
